# Generated by Django 4.1.2 on 2022-10-15 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=20)),
                ('self_employed', models.BooleanField(null=True)),
                ('family_history', models.BooleanField(null=True)),
                ('treatment', models.BooleanField(null=True)),
                ('work_interfere', models.CharField(choices=[('Never', 'Never'), ('Often', 'Often'), ('Rarely', 'Rarely')], max_length=7, null=True)),
                ('no_employees', models.IntegerField(null=True)),
                ('remote_work', models.BooleanField(null=True)),
                ('tech_company', models.BooleanField(null=True)),
                ('benefits', models.BooleanField(null=True)),
                ('care_options', models.BooleanField(null=True)),
                ('wellness_program', models.BooleanField(null=True)),
                ('seek_help', models.BooleanField(null=True)),
                ('anoymity', models.BooleanField(null=True)),
                ('leave', models.CharField(choices=[('SE', 'Somewhat easy'), ('DK', "Don't know"), ('SD', 'Somewhat difficult')], max_length=4, null=True)),
                ('mental_health_consequence', models.BooleanField(null=True)),
                ('phys_health_consequence', models.BooleanField(null=True)),
                ('coworkers', models.CharField(choices=[('some', 'Some of them'), ('No', 'No'), ('Yes', 'Yes')], max_length=4, null=True)),
                ('mental_health_interview', models.BooleanField(null=True)),
                ('phys_health_interview', models.BooleanField(null=True)),
                ('mental_vs_physical', models.BooleanField(null=True)),
                ('obs_consequence', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
