# Generated by Django 4.1.2 on 2022-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='complete',
            field=models.BooleanField(null=True),
        ),
    ]
