# Generated by Django 4.1.2 on 2022-10-15 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_form_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=12)),
                ('pin', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
