# Generated by Django 4.1.2 on 2022-10-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_form_complete_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='timings',
            field=models.CharField(default='24x7', max_length=50),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='pin',
            field=models.IntegerField(max_length=6),
        ),
    ]
