# Generated by Django 4.1.2 on 2022-10-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_therapist_timings_therapist_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='coworkers',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mental_health_consequence',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mental_health_interview',
        ),
        migrations.RemoveField(
            model_name='form',
            name='mental_vs_physical',
        ),
        migrations.RemoveField(
            model_name='form',
            name='no_employees',
        ),
        migrations.RemoveField(
            model_name='form',
            name='obs_consequence',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phys_health_consequence',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phys_health_interview',
        ),
        migrations.RemoveField(
            model_name='form',
            name='remote_work',
        ),
        migrations.RemoveField(
            model_name='form',
            name='seek_help',
        ),
        migrations.RemoveField(
            model_name='form',
            name='self_employed',
        ),
        migrations.RemoveField(
            model_name='form',
            name='tech_company',
        ),
        migrations.RemoveField(
            model_name='form',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='form',
            name='wellness_program',
        ),
        migrations.AlterField(
            model_name='form',
            name='work_interfere',
            field=models.CharField(choices=[('Never', 'Never'), ('Often', 'Often'), ('Rarely', 'Rarely')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='from_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='to_time',
            field=models.CharField(max_length=50),
        ),
    ]
